---
kind: pipeline
type: docker
name: deploy dev

trigger:
  branch:
    - dev
  event:
    include:
      - push

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ge_dev_host
      username:
        from_secret: ge_dev_ssh_user
      password:
        from_secret: ge_dev_ssh_password
      port: 22
      command_timeout: 10m
      script:
        - cd /home/dev/gafi-mp/gafi-market-be
        - git fetch origin +${DRONE_COMMIT_REF}
        - git checkout ${DRONE_COMMIT} 
        - cargo build -r
        - pm2 reload gafi-worker
        - pm2 reload gafi-api