[workspace]
members = [
  "worker",
  "backend",
  "shared",
]

[workspace.package]
authors = ["Grindy"]
description = "Gafi marketplace"
edition = "2021"
name = "gafi-market"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
