name: Build backend

permissions:
  contents: read

# Controls when the action will run.
on: 
  push:
    tags:
      - v[0-9]+.*

jobs:
  build-image:
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Login to Docker hub using the credentials stored in the repository secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install linux dependencies
        run: sudo apt-get install -y clang libssl-dev llvm libudev-dev protobuf-compiler
  
      - name: Install Rust
        run: |
          rustup update stable --no-self-update

       # Rust cache
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build-backend"

      - name: Build
        run: |
          cargo build -r -p backend
          cp ./target/release/backend ./build/backend 

      # Build and push 2 images, One with the version tag and the other with latest tag
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build/dockerfile-backend
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:gafi-market-backend-${{ github.ref_name }}
            ${{ env.DOCKER_REPO }}:gafi-market-backend-latest

