name: Check backend

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, dev]
    paths:
      - "backend/**"
      - "shared/**"

  pull_request:
    branches: [master, dev]
    paths:
      - "backend/**"
      - "shared/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install linux dependencies
        run: sudo apt-get install -y clang libssl-dev llvm libudev-dev protobuf-compiler

      - name: Install Rust
        run: |
          rustup update stable --no-self-update

      # Rust cache
      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci

      - name: Check Build
        run: |
          cargo check -r -p backend

      - name: Unit-Test
        run: |
          cargo test -r -p backend
